image: node:latest

pages:
  script:
    - npm install  # Install dependencies
    - npm run build  # Build the project
    - mv build public  # Move the build directory to public
  artifacts:
    paths:
      - public  # Specify the directory to publish
  only:
    - working  # Run this job only for the 'working' branch
